---
- name: here we add the master cluster
  hosts: master
  become: true
  tasks:
    - name: here we turn off the firewall state
      command: sudo ufw disable
    - name: here we turn off the swap
      command: swapoff -a; sed -i '/swap/d' /etc/fstab
    - name: here we turn add the iptables rules
      command: cat >>/etc/sysctl.d/kubernetes.conf<<EOF
               net.bridge.bridge-nf-call-ip6tables = 1
               net.bridge.bridge-nf-call-iptables = 1
               EOF
               sysctl --system
         
    - name: here we initialize the cluster
      command: kubeadm init --apiserver-advertise-address=192.168.43.91 --pod-network-cidr=192.168.0.0/16  --ignore-preflight-errors=all
    - name: here we copy the file
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/mukunth/mylocal.conf
        remote_src: yes
        owner: mukunth
...
